### ISSUE TITLE
Any plans to adapt to the new Org export framework

### ISSUE THREAD

**Issue by tarsius** [mlf176f2/org-readme#19]
`org-html.el` is no longer part of Org, as the old export framework that it was part of has been removed. Do you intend to adapt this for the new export framework in recent Org versions?

**Comment by mattfidler** [comment]
I have stopped using this, so I'm likely not going to adapt the more recent framework.  @vapniks may still use it and adapt it.

**Comment by tarsius** [comment]
Alright. I will wait a little for @vapniks, and if he doesn't state that he's going to adapt this, then I will remove it from Melpa and move it from the Emacsmirror to the Emacsattic.

**Comment by mattfidler** [comment]
Do you know if anyone downloaded it recently.  I saw over 1000 downloads on melpa.  It may be more popular than I anticipated...?

**Comment by tarsius** [comment]
Unfortunately it's not possible to know when those downloads were made. There's an issue about that on the Melpa issue tracker: https://github.com/melpa/melpa/issues/4376. Also relevant is the other issue mentioned there (https://github.com/melpa/melpa/issues/4384).

So the idea is that we remove it, and if someone complains then it can be added back.

/cc @purcell

**Comment by vapniks** [comment]
`org-html` is not required, it's optional. So I'm not sure it needs to be adapted. I haven't tested it fully, but it seems to be working.

**Comment by tarsius** [comment]
I just took a closer look, and it indeed seems that `org-html` is only required for backward compatibility. If that feature is not available, then `(org-export-replace-region-by 'html)` is used instead of `org-replace-region-by-html`.
